// <auto-generated />
using System;
using AksTyreProduction.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AksTyreProduction.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006123705_AddWorkerJobWritePermission")]
    partial class AddWorkerJobWritePermission
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("AksTyreProduction.Web.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanWriteJobs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RolesCsv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.AuditEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RetreadJobId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TyreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.Dispatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DispatchDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RetreadJobId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RetreadJobId")
                        .IsUnique();

                    b.ToTable("Dispatches");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MarkupPercentSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductionCostSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetreadJobId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SellingPriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RetreadJobId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BatchTrackingRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentUnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantityOnHand")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReorderLevel")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.MaterialBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantityRemaining")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LotNumber");

                    b.HasIndex("MaterialId");

                    b.ToTable("MaterialBatches");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.MaterialUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaterialBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetreadJobId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StationTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitCostSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaterialBatchId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("RetreadJobId");

                    b.HasIndex("StationTransactionId");

                    b.ToTable("MaterialUsages");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LabourRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.PhotoAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RetreadJobId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StationTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RetreadJobId");

                    b.ToTable("PhotoAttachments");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.Repair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatchSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetreadJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RetreadJobId");

                    b.ToTable("Repairs");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.RetreadJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerVisibleRejectionNote")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstimatedCompletion")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MarkupPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("QcOperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QcOperatorNameSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("QcPassedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadyForDispatchAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetreadNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TyreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QcOperatorId");

                    b.HasIndex("TyreId", "RetreadNumber")
                        .IsUnique();

                    b.ToTable("RetreadJobs");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.StationTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LabourCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LabourRateSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetreadJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Station")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("RetreadJobId");

                    b.ToTable("StationTransactions");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.Tyre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AksTyreId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CasingCondition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsScrapped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalTreadPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScrapReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScrappedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AksTyreId")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("SerialNumber");

                    b.ToTable("Tyres");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.Dispatch", b =>
                {
                    b.HasOne("AksTyreProduction.Web.Models.RetreadJob", "RetreadJob")
                        .WithOne("Dispatch")
                        .HasForeignKey("AksTyreProduction.Web.Models.Dispatch", "RetreadJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RetreadJob");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.Invoice", b =>
                {
                    b.HasOne("AksTyreProduction.Web.Models.RetreadJob", "RetreadJob")
                        .WithOne("Invoice")
                        .HasForeignKey("AksTyreProduction.Web.Models.Invoice", "RetreadJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RetreadJob");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.MaterialBatch", b =>
                {
                    b.HasOne("AksTyreProduction.Web.Models.Material", "Material")
                        .WithMany("Batches")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.MaterialUsage", b =>
                {
                    b.HasOne("AksTyreProduction.Web.Models.MaterialBatch", "MaterialBatch")
                        .WithMany()
                        .HasForeignKey("MaterialBatchId");

                    b.HasOne("AksTyreProduction.Web.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AksTyreProduction.Web.Models.RetreadJob", "RetreadJob")
                        .WithMany("MaterialUsages")
                        .HasForeignKey("RetreadJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AksTyreProduction.Web.Models.StationTransaction", "StationTransaction")
                        .WithMany("MaterialUsages")
                        .HasForeignKey("StationTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Material");

                    b.Navigation("MaterialBatch");

                    b.Navigation("RetreadJob");

                    b.Navigation("StationTransaction");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.PhotoAttachment", b =>
                {
                    b.HasOne("AksTyreProduction.Web.Models.RetreadJob", "RetreadJob")
                        .WithMany("Photos")
                        .HasForeignKey("RetreadJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RetreadJob");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.Repair", b =>
                {
                    b.HasOne("AksTyreProduction.Web.Models.RetreadJob", "RetreadJob")
                        .WithMany("Repairs")
                        .HasForeignKey("RetreadJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RetreadJob");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.RetreadJob", b =>
                {
                    b.HasOne("AksTyreProduction.Web.Models.Operator", "QcOperator")
                        .WithMany()
                        .HasForeignKey("QcOperatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AksTyreProduction.Web.Models.Tyre", "Tyre")
                        .WithMany("RetreadJobs")
                        .HasForeignKey("TyreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QcOperator");

                    b.Navigation("Tyre");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.StationTransaction", b =>
                {
                    b.HasOne("AksTyreProduction.Web.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId");

                    b.HasOne("AksTyreProduction.Web.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AksTyreProduction.Web.Models.RetreadJob", "RetreadJob")
                        .WithMany("StationTransactions")
                        .HasForeignKey("RetreadJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Operator");

                    b.Navigation("RetreadJob");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.Tyre", b =>
                {
                    b.HasOne("AksTyreProduction.Web.Models.Customer", "Customer")
                        .WithMany("Tyres")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.Customer", b =>
                {
                    b.Navigation("Tyres");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.Material", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.RetreadJob", b =>
                {
                    b.Navigation("Dispatch");

                    b.Navigation("Invoice");

                    b.Navigation("MaterialUsages");

                    b.Navigation("Photos");

                    b.Navigation("Repairs");

                    b.Navigation("StationTransactions");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.StationTransaction", b =>
                {
                    b.Navigation("MaterialUsages");
                });

            modelBuilder.Entity("AksTyreProduction.Web.Models.Tyre", b =>
                {
                    b.Navigation("RetreadJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
